In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
sns.set()
plt.rcParams['font.sans-serif'] = ['SimHei'] # 显示中文标题 
plt.rcParams['axes.unicode_minus'] = False # 正常显示正负号

* 问题：1：在总表里筛选数据，接着创建唯一ID，最后把其他子表中总表没有的内容根据唯一ID拼接到总表后面
* 过滤：空值过滤(删整行),ST(不景气的)过滤,范围过滤(筛选2.5~97.5%间的连续数据,避免极端影响)
# 1.读数据

In [2]:
df1 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\roa.xlsx')
df2 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\独董比例.xlsx')
df3 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\固定资产.xlsx')
df4 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\营收增长率.xlsx')
df5 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\资产负债率.xlsx')
df6 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\总资产----同时也是班级的表，其他五个是年纪的表.xlsx')

In [3]:
df6.head()

    Stkcd      Reptdt Stknme Nindcd Nindnme   A001000000
0    证券代码      统计截止日期   证券简称   行业代码    行业名称          总资产
1  000004  2014-12-31   国农科技    C27   医药制造业  3.38283e+08
2  000004  2015-12-31   国农科技    C27   医药制造业  3.98674e+08
3  000004  2016-12-31   国农科技    C27   医药制造业  2.23716e+08
4  000004  2017-12-31   国农科技    C27   医药制造业  2.68844e+08

# 2.筛选12.31和A数据

In [4]:
def myfitter(col, ends, df):
    ###要过滤的列,过滤内容,df###
    return df[[t.endswith(ends) for t in df.iloc[:,col].values]]

In [5]:
df1 = myfitter(1,'12-31',df1)
df2 = myfitter(1,'12-31',df2)
df3 = myfitter(1,'12-31',df3)
df4 = myfitter(1,'12-31',df4)
df5 = myfitter(1,'12-31',df5)
df6 = myfitter(1,'12-31',df6)

df1 = myfitter(2,'A',df1)
df3 = myfitter(2,'A',df3)
df4 = myfitter(2,'A',df4)
df5 = myfitter(2,'A',df5)

# 3.ID生成

In [6]:
def createId(df,col1,col2):
    df['ID'] = df.iloc[:,col1]+df.iloc[:,col2]

In [7]:
createId(df1,0,1)
createId(df2,0,1)
createId(df3,0,1)
createId(df4,0,1)
createId(df5,0,1)
createId(df6,0,1)

# 4.合并表

In [8]:
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df4.columns)
print(df5.columns)
print(df6.columns)

Index(['Stkcd', 'Accper', 'Typrep', 'F050203B', 'ID'], dtype='object')
Index(['Stkcd', 'Reptdt', 'Stknme', 'dir', 'ID'], dtype='object')
Index(['Stkcd', 'Accper', 'Typrep', 'C002006000', 'ID'], dtype='object')
Index(['Stkcd', 'Accper', 'Typrep', 'F081701B', 'ID'], dtype='object')
Index(['Stkcd', 'Accper', 'Typrep', 'F011201A', 'ID'], dtype='object')
Index(['Stkcd', 'Reptdt', 'Stknme', 'Nindcd', 'Nindnme', 'A001000000', 'ID'], dtype='object')

In [9]:
# 创造空列
def createNoColList(df1,df2):
    colList = [str for str in df2.columns if str not in df1.columns]
    for str in colList:
        df1[str] = None

In [10]:
createNoColList(df6,df1)
createNoColList(df6,df2)
createNoColList(df6,df3)
createNoColList(df6,df4)
createNoColList(df6,df5)

In [11]:
df6.head()

,Stkcd,Reptdt,Stknme,Nindcd,Nindnme,A001000000,ID,Accper,Typrep,F050203B,dir,C002006000,F081701B,F011201A
1,000004,2014-12-31,国农科技,C27,医药制造业,3.38283e+08,0000042014-12-31,None,None,None,None,None,None,None
2,000004,2015-12-31,国农科技,C27,医药制造业,3.98674e+08,0000042015-12-31,None,None,None,None,None,None,None
3,000004,2016-12-31,国农科技,C27,医药制造业,2.23716e+08,0000042016-12-31,None,None,None,None,None,None,None
4,000004,2017-12-31,国农科技,C27,医药制造业,2.68844e+08,0000042017-12-31,None,None,None,None,None,None,None
5,000004,2018-12-31,国农科技,C27,医药制造业,3.51177e+08,0000042018-12-31,None,None,None,None,None,None,None

* 根据ID筛选填充

In [12]:
df1.head()

        Stkcd      Accper Typrep  F050203B                ID
14889  002107  2014-12-31      A  0.055642  0021072014-12-31
14891  002538  2014-12-31      A  0.047583  0025382014-12-31
14893  002654  2014-12-31      A  0.044426  0026542014-12-31
14895  600593  2014-12-31      A   0.05516  6005932014-12-31
14897  300358  2014-12-31      A  0.124917  3003582014-12-31

In [13]:
# 把ID和索引做成字典方便检索
dt = dict(zip(df6['ID'].values,df6['ID'].index))

In [14]:
# 找出有ID的两个表的索引
def combineDf(df,df1):
    for idx in df1.index:
        id =df1.loc[idx,'ID']
        if id in dt:
            # print(idx)
            # 赋值
            for col in df1.columns:
                df.loc[dt[id],col] = df1.loc[idx,col]
    return df

In [15]:
df6 = combineDf(df6,df1)
df6 = combineDf(df6,df2)
df6 = combineDf(df6,df3)
df6 = combineDf(df6,df4)
df6 = combineDf(df6,df5)

In [16]:
# df6.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\中间表.xlsx')

# 5.空值过滤,ST过滤,范围过滤

In [17]:
# 空值过滤
# df6 = df6.dropna()

In [18]:
df6.head()

,Stkcd,Reptdt,Stknme,Nindcd,Nindnme,A001000000,ID,Accper,Typrep,F050203B,dir,C002006000,F081701B,F011201A
1,000004,2014-12-31,国农科技,C27,医药制造业,3.38283e+08,0000042014-12-31,2014-12-31,A,0.053838,0.333333,11212298,0.107499,0.534754
2,000004,2015-12-31,国农科技,C27,医药制造业,3.98674e+08,0000042015-12-31,2015-12-31,A,0.018609,0.333333,4134756,0.494308,0.590402
3,000004,2016-12-31,国农科技,C27,医药制造业,2.23716e+08,0000042016-12-31,2016-12-31,A,0.127625,0.333333,2.24494e+06,1.38821,0.203456
4,000004,2017-12-31,国农科技,C27,医药制造业,2.68844e+08,0000042017-12-31,2017-12-31,A,0.023925,0.333333,5.8471e+06,-0.518178,0.315247
5,000004,2018-12-31,国农科技,C27,医药制造业,3.51177e+08,0000042018-12-31,2018-12-31,A,-0.069716,0.333333,1.75371e+07,1.64685,0.477966

In [19]:
# ST过滤
df6 = df6[[t.find('ST')==-1 for t in df6.iloc[:,2].values]]

In [20]:
# 范围过滤
def fitterMiAndMx(df,col,rate1,rate2):
    sortL = sorted(df[col].values)
    mi = sortL[int(len(sortL)*rate1)]
    mx = sortL[int(len(sortL)*rate2)]
    return df[[t>mi and t<mx for t in df.loc[:,col].values]]

In [21]:
#df6 = fitterMiAndMx(df6,'A001000000',0.025,0.975)
#df6 = fitterMiAndMx(df6,'F050203B',0.025,0.975)
#df6 = fitterMiAndMx(df6,'dir',0.025,0.975)
#df6 = fitterMiAndMx(df6,'C002006000',0.025,0.975)
#df6 = fitterMiAndMx(df6,'F081701B',0.025,0.975)
#df6 = fitterMiAndMx(df6,'F011201A',0.025,0.975)

In [22]:
# df6.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\完成表.xlsx')

# 二、分表处理(按年份分表,小表取最大值作为代表,其他删除)
* 对分出来的6个表的每个企业取最近投资的行数据(称为最近增量表吧)

In [142]:
df7 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\产融集合(1).xlsx')

In [143]:
# 按年份分表
g = list(df7.groupby('year'))

In [144]:
df2013 = g[0][1]
df2014 = g[1][1]
df2015 = g[2][1]
df2016 = g[3][1]
df2017 = g[4][1]
df2018 = g[5][1]

In [145]:
# 取最大值作为代表,其他删除
def getMaxAndFitter(df,Name,col):
    dt = {}
    # 筛选企业最大值
    for name,val in zip(df.loc[:,Name].values,df.loc[:,col].values):
        if name not in dt:
            dt[name] = val
        else:
            dt[name] = max(dt[name],val)
    # 过滤
    return df[[val>=dt[name] for name,val in zip(df.loc[:,Name].values,df.loc[:,col].values)]]

In [146]:
df2013 = getMaxAndFitter(df2013,'名称','持有数量(万股/份)')
df2014 = getMaxAndFitter(df2014,'名称','持有数量(万股/份)')
df2015 = getMaxAndFitter(df2015,'名称','持有数量(万股/份)')
df2016 = getMaxAndFitter(df2016,'名称','持有数量(万股/份)')
df2017 = getMaxAndFitter(df2017,'名称','持有数量(万股/份)')
df2018 = getMaxAndFitter(df2018,'名称','持有数量(万股/份)')

df2013 = getMaxAndFitter(df2013,'名称','持股比例')
df2014 = getMaxAndFitter(df2014,'名称','持股比例')
df2015 = getMaxAndFitter(df2015,'名称','持股比例')
df2016 = getMaxAndFitter(df2016,'名称','持股比例')
df2017 = getMaxAndFitter(df2017,'名称','持股比例')
df2018 = getMaxAndFitter(df2018,'名称','持股比例')

In [147]:
df2015

,代码,名称,金融机构简称,金融机构类型,持有数量(万股/份),持股比例,投资金额,期末余额,截止日期,year
278,000690.SZ,宝新能源,广东南粤银行,银行,69978.003000,11.2500,9.540452e+08,9.540452e+08,2015-12-31,2015
281,600167.SH,联美控股,国任财险,保险,18000.000000,6.0000,2.340000e+08,2.340000e+08,2015-12-31,2015
282,600200.SH,江苏吴中,江苏银行,银行,5191.088500,0.5000,3.602859e+07,3.602859e+07,2015-12-31,2015
283,600261.SH,阳光照明,长城证券,证券,1700.000000,0.6100,1.020000e+08,9.645769e+07,2015-12-31,2015
285,600293.SH,三峡新材,湖北银行,银行,1089.805100,0.5800,1.479600e+07,1.479600e+07,2015-12-31,2015
286,600331.SH,宏达股份,四川信托,信托,55401.280565,22.1605,2.470000e+08,1.400418e+09,2015-12-31,2015
287,600352.SH,浙江龙盛,锦州银行,银行,0.000000,0.0000,2.000000e+08,0.000000e+00,2015-12-31,2015
288,600518.SH,ST康美,广发基金,基金公司,1200.000000,9.4580,7.656000e+07,3.971281e+08,2015-12-31,2015
289,600693.SH,东百集团,福建海峡银行,银行,537.154300,0.1700,1.034800e+06,4.449640e+06,2015-12-31,2015
290,600738.SH,兰州民百,兰州银行,银行,5260.380000,1.0300,5.950000e+07,1.160821e+08,2015-12-31,2015
292,600873.SH,梅花生物,西藏银行,银行,12800.000000,4.2414,1.570000e+08,1.570000e+08,2015-12-31,2015
294,601011.SH,宝泰隆,龙江银行,银行,0.000000,0.3463,8.000000e+06,1.636332e+07,2015-12-31,2015
295,601155.SH,新城控股,苏州银行,银行,3000.000000,1.0000,1.560000e+08,1.700000e+08,2015-12-31,2015
296,603001.SH,奥康国际,温州民商银行,银行,0.000000,9.9000,1.980000e+08,0.000000e+00,2015-12-31,2015
297,603077.SH,和邦生物,乐山市商业银行,银行,5678.897000,3.1200,3.000000e+07,0.000000e+00,2015-12-31,2015
298,603968.SH,醋化股份,江苏银行,银行,0.000000,0.0000,2.230000e+06,2.230000e+06,2015-12-31,2015

* 最近增量表:把本年的数据依次合并到上一年即可

In [150]:
def insertAndCombine(df,df1,Name):
    lastDf = df1.copy()
    print("前:",lastDf.shape)
    dt = dict(zip(df[Name].values,df[Name].index))
    lastDt = dict(zip(lastDf[Name].values,lastDf[Name].index))
    # 本年,上年
    addDf = DataFrame()
    for name in df.loc[:,Name]:
        # print(name)
        if name in lastDf[Name].values:
            # 上年有,替换
            lastDf.loc[lastDt[name]] = df.loc[dt[name]]
        else:
            # 追加
            lastDf.append(df.loc[dt[name]])
            print(name,lastDf.shape)
            #print(df.loc[dt[name]])
    #print(addDf)
    #print(lastDf)
    #return pd.concat([lastDf,addDf])
    print('变化后',lastDf.shape)
    return lastDf

In [151]:
d2014 = insertAndCombine(df2014,df2013,'名称')
df2015 = insertAndCombine(df2015,df2014,'名称')
#df2016 = insertAndCombine(df2016,df2015,'名称')
#df2017 = insertAndCombine(df2017,df2016,'名称')
#df2018 = insertAndCombine(df2018,df2017,'名称')

(186, 10)
(186, 10)
(13, 10)
(13, 10)

In [141]:
df2014

,代码,名称,金融机构简称,金融机构类型,持有数量(万股/份),持股比例,投资金额,期末余额,截止日期,year
256,000159.SZ,国际实业,乌鲁木齐银行,银行,766.76390,0.2600,1.686881e+07,1.686881e+07,2014-12-31,2014
257,000301.SZ,东方盛虹,江苏苏州农商银行,银行,1239.76120,1.2400,5.000000e+06,5.000000e+06,2014-12-31,2014
262,000333.SZ,美的集团,顺德农商行,银行,32887.41600,9.4000,1.263774e+09,1.263774e+09,2014-12-31,2014
265,000426.SZ,兴业矿业,中诚信托,信托,4000.00000,1.6300,6.441481e+07,6.441481e+07,2014-12-31,2014
266,000513.SZ,丽珠集团,珠海华润银行,银行,8493.60000,1.5065,9.532576e+07,7.532576e+07,2014-12-31,2014
269,000516.SZ,国际医学,广东华兴银行,银行,12000.00000,2.4000,1.560000e+08,1.560000e+08,2014-12-31,2014
270,000540.SZ,中天金融,贵州银行,银行,7100.00000,0.9900,9.443000e+07,9.443000e+07,2014-12-31,2014
272,000559.SZ,万向钱潮,万向财务,财务,24000.00000,17.8300,2.400000e+08,2.968820e+08,2014-12-31,2014
273,000593.SZ,大通燃气,中铁信托,信托,453.79592,0.2300,4.980000e+06,4.341650e+06,2014-12-31,2014
274,000603.SZ,盛达资源,兰州银行,银行,5000.00000,1.3800,1.260000e+08,1.260000e+08,2014-12-31,2014
275,000615.SZ,京汉股份,湖北银行,银行,1766.74390,0.7900,1.584000e+07,1.584000e+07,2014-12-31,2014
276,000620.SZ,新华联,长沙银行,银行,14908.33090,5.7000,3.230165e+08,7.982358e+08,2014-12-31,2014
277,000626.SZ,远大控股,宁波东海银行,银行,9831.31700,9.6600,1.685500e+07,8.042203e+07,2014-12-31,2014

In [108]:
t = df2014.iloc[1,:]

In [115]:
t.index

Index(['代码', '名称', '金融机构简称', '金融机构类型', '持有数量(万股/份)', '持股比例', '投资金额', '期末余额',
       '截止日期', 'year'],
      dtype='object')

In [120]:
print(t)
t1 = DataFrame()
t1.column = t.index
t1.append(t)
print(t1)

代码                      000301.SZ
名称                           东方盛虹
金融机构简称                   江苏苏州农商银行
金融机构类型                         银行
持有数量(万股/份)                1239.76
持股比例                         1.24
投资金额                        5e+06
期末余额                        5e+06
截止日期          2014-12-31 00:00:00
year                         2014
Name: 2, dtype: object
Empty DataFrame
Columns: []
Index: []

C:\Users\WuChuPeng\data_for_wuchupeng\software_install\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  This is separate from the ipykernel package so we can avoid doing imports until

In [118]:
df2018.append(t)

,代码,名称,金融机构简称,金融机构类型,持有数量(万股/份),持股比例,投资金额,期末余额,截止日期,year
328,600293.SH,三峡新材,湖北银行,银行,1089.805100,0.5800,1.479600e+07,1.479600e+07,2018-12-31,2018
329,600331.SH,宏达股份,四川信托,信托,77561.780565,22.1605,2.470000e+08,2.024276e+09,2018-12-31,2018
330,600439.SH,瑞贝卡,中原银行,银行,10912.559800,0.0000,0.000000e+00,2.390396e+08,2018-12-31,2018
331,600496.SH,精工钢构,瑞丰银行,银行,0.000000,4.1600,3.230000e+08,4.280000e+08,2018-12-31,2018
332,600596.SH,新安股份,杭州工商信托,信托,0.000000,0.0000,0.000000e+00,6.450000e+06,2018-12-31,2018
333,600738.SH,兰州民百,兰州银行,银行,0.000000,1.0300,5.950000e+07,1.160821e+08,2018-12-31,2018
335,600873.SH,梅花生物,廊坊开发区融商村镇银行,银行,0.000000,8.0000,0.000000e+00,4.000000e+06,2018-12-31,2018
336,600884.SH,杉杉股份,浙江稠州商业银行,银行,24726.000000,7.0600,6.827779e+08,1.233027e+09,2018-12-31,2018
337,601155.SH,新城控股,苏州银行,银行,0.000000,1.0000,0.000000e+00,1.971000e+08,2018-12-31,2018
338,603077.SH,和邦生物,乐山市商业银行,银行,5678.897000,2.3700,8.002419e+07,0.000000e+00,2018-12-31,2018
2,000301.SZ,东方盛虹,江苏苏州农商银行,银行,1239.761200,1.2400,5.000000e+06,5.000000e+06,2014-12-31,2014

In [34]:
print(df2018)

            代码     名称       金融机构简称 金融机构类型   持有数量(万股/份)     持股比例          投资金额  \
1    000159.SZ   国际实业       乌鲁木齐银行     银行    766.76390   0.2600  1.686881e+07
2    000301.SZ   东方盛虹     江苏苏州农商银行     银行   1239.76120   1.2400  5.000000e+06
3    000333.SZ   美的集团        顺德农商行     银行  32887.41600   9.4000  1.263774e+09
10   000426.SZ   兴业矿业         中诚信托     信托   4000.00000   1.6300  6.441481e+07
12   000513.SZ   丽珠集团       珠海华润银行     银行   8493.60000   1.5065  9.532576e+07
13   000516.SZ   国际医学       广东华兴银行     银行  12000.00000   2.4000  1.560000e+08
15   000540.SZ   中天金融         贵州银行     银行   7100.00000   0.9900  9.443000e+07
17   000559.SZ   万向钱潮         万向财务     财务  24000.00000  17.8300  2.400000e+08
18   000593.SZ   大通燃气         中铁信托     信托    453.79592   0.2300  4.980000e+06
19   000603.SZ   盛达资源         兰州银行     银行   5000.00000   1.3800  1.260000e+08
20   000609.SZ   中迪投资         华润信托     信托      0.00000   0.0000  2.000000e+07
21   000615.SZ   京汉股份         湖北银行     银行   1766.74390   0.7900  1.584000e+07
22   000620.SZ    新华联         长沙银行     银行  14908.33090   5.7000  3.230165e+08
23   000626.SZ   远大控股       宁波东海银行     银行   9831.31700   9.6600  1.685500e+07
24   000668.SZ   荣丰控股         长沙银行     银行   4745.25140   2.0500  1.484413e+07
25   000678.SZ   襄阳轴承         湖北银行     银行     20.00000   0.0100  2.000000e+05
27   000690.SZ   宝新能源       广东南粤银行     银行  69978.00300  11.2500  9.540452e+08
29   000700.SZ   模塑科技         江苏银行     银行  10044.24980   0.9700  7.260000e+07
30   000703.SZ   恒逸石化         浙商银行     银行  24000.00000   2.0900  3.816000e+08
31   000732.SZ   泰禾集团      福建福州农商行     银行    200.00000   0.3800  4.140000e+06
32   000766.SZ   通化金马        长春农商行     银行  12000.00000  10.0000  3.000000e+07
34   000782.SZ   美达股份      江门新会农商行     银行   2160.00000   1.8000  5.940000e+07
36   000785.SZ   居然之家         汉口银行     银行   2519.04000   0.6100  2.048000e+07
37   000796.SZ   凯撒旅业         永安财险     保险   2000.00000   0.7500  2.000000e+07
38   000813.SZ   德展健康         金新信托     信托   5000.00000   8.7800  6.500000e+07
39   000818.SZ   航锦科技         锦州银行     银行   2000.00000   0.5100  2.000000e+07
40   000821.SZ   京山轻机         天风证券     证券   3017.70000   1.7300  2.614248e+07
41   000876.SZ    新希望         民生保险     保险  20352.00000   5.0900  2.111960e+08
43   000890.SZ    法尔胜      江苏阜宁农商行     银行   1500.00000   5.0000  1.950000e+07
44   000902.SZ    新洋丰         上海银行     银行     59.84540   0.0100  4.099000e+05
..         ...    ...          ...    ...          ...      ...           ...
213  600566.SH   济川药业      江苏泰兴农商行     银行   2000.00000   4.0000  3.000000e+07
214  600571.SH    信雅达         财通证券     证券   3857.14290   2.1400  7.530000e+07
215  600580.SH   卧龙电驱         绍兴银行     银行   7400.00000   7.5200  1.110000e+08
217  600586.SH   金晶科技      山东滕州农商行     银行   3210.00000   6.1000  3.210000e+07
218  600595.SH  *ST中孚     巩义浦发村镇银行     银行   1500.00000  10.0000  1.560000e+07
220  600652.SH  *ST游久       北京国际信托     信托  11600.00000   8.2900  1.424000e+08
221  600654.SH  *ST中安         上海银行     银行    295.03680   0.0700  5.055272e+06
222  600655.SH   豫园股份         上海银行     银行   3489.58980   0.8242  7.133121e+07
223  600678.SH   四川金顶      乐山市商业银行     银行    579.36780   0.3200  3.000000e+06
224  600682.SH   南京新百         南京证券     证券   3723.04760   1.9600  1.073365e+08
227  600694.SH   大商股份         锦州银行     银行      0.00000   0.3900  4.632153e+06
228  600711.SH   盛屯矿业         厦门银行     银行     11.58400   0.0000  2.101410e+05
229  600721.SH  *ST百花       乌鲁木齐银行     银行      6.47800   0.0030  3.000000e+04
230  600770.SH   综艺股份         长安保险     保险      0.00000  11.7600  1.100000e+08
235  600778.SH   友好集团       乌鲁木齐银行     银行   1528.68840   0.3700  1.481000e+07
236  600785.SH   新华百货         宁夏银行     银行   1330.00000   0.8000  1.000000e+07
237  600818.SH   中路股份         先锋期货     期货   2000.00000  20.0000  2.000000e+07
238  600865.SH   百大集团         杭州银行     银行   1500.00000   0.9000  1.350108e+08
239  600872.SH   中炬高新   中山东凤珠江村镇银行     银行   1500.00000  10.0000  1.500000e+07
240  600873.SH   梅花生物  廊坊开发区融商村镇银行     银行      0.00000   8.0000  0.000000e+00
242  600882.SH   妙可蓝多         中泰证券     证券   1500.36000   0.2900  5.366728e+07
243  600884.SH   杉杉股份     浙江稠州商业银行     银行  24726.00000   7.0600  6.827779e+08
244  600896.SH   览海医疗       中远海运财务     财务   3000.00000   5.0000  3.000000e+07
245  601011.SH    宝泰隆         龙江银行     银行      0.00000   0.3463  8.000000e+06
247  601216.SH   君正集团         天弘基金   基金公司   6480.00000  36.0000  3.120000e+07
250  601777.SH   力帆股份         安诚财险     保险  10000.00000   2.4500  1.000000e+08
251  601890.SH   亚星锚链   江苏靖江润丰村镇银行     银行   1081.56400   8.3300  1.000000e+07
252  603077.SH   和邦生物      乐山市商业银行     银行   5678.89700   2.3700  8.002419e+07
253  603288.SH   海天味业         广发银行     银行      5.39070   0.0004  1.000000e+05
254  603366.SH   日出东方         江苏银行     银行    100.00000   0.0100  1.000000e+06

             期末余额       截止日期  year
1    1.686881e+07 2014-12-31  2014
2    5.000000e+06 2014-12-31  2014
3    1.263774e+09 2014-12-31  2014
10   6.441481e+07 2014-12-31  2014
12   7.532576e+07 2014-12-31  2014
13   1.560000e+08 2014-12-31  2014
15   9.443000e+07 2014-12-31  2014
17   2.968820e+08 2014-12-31  2014
18   4.341650e+06 2014-12-31  2014
19   1.260000e+08 2014-12-31  2014
20   2.007342e+07 2013-12-31  2013
21   1.584000e+07 2014-12-31  2014
22   7.982358e+08 2014-12-31  2014
23   8.042203e+07 2014-12-31  2014
24   1.484413e+07 2013-12-31  2013
25   2.000000e+05 2013-12-31  2013
27   9.540452e+08 2015-12-31  2015
29   7.260000e+07 2013-12-31  2013
30   3.816000e+08 2013-12-31  2013
31   4.140000e+06 2013-12-31  2013
32   1.396500e+08 2013-12-31  2013
34   5.940000e+07 2013-12-31  2013
36   2.048000e+07 2013-12-31  2013
37   2.000000e+07 2013-12-31  2013
38   0.000000e+00 2013-12-31  2013
39   2.000000e+07 2013-12-31  2013
40   2.614248e+07 2013-12-31  2013
41   2.111960e+08 2013-12-31  2013
43   1.950000e+07 2013-12-31  2013
44   4.099000e+05 2013-12-31  2013
..            ...        ...   ...
213  3.000000e+07 2013-12-31  2013
214  0.000000e+00 2013-12-31  2013
215  1.110000e+08 2013-12-31  2013
217  3.210000e+07 2013-12-31  2013
218  1.560000e+07 2013-12-31  2013
220  1.424000e+08 2013-12-31  2013
221  5.055272e+06 2013-12-31  2013
222  7.133121e+07 2013-12-31  2013
223  8.103527e+06 2013-12-31  2013
224  1.219954e+08 2013-12-31  2013
227  4.632153e+06 2013-12-31  2013
228  2.101410e+05 2013-12-31  2013
229  3.000000e+04 2013-12-31  2013
230  1.100000e+08 2013-12-31  2013
235  1.481000e+07 2017-12-31  2017
236  1.000000e+07 2013-12-31  2013
237  2.000000e+07 2013-12-31  2013
238  1.350108e+08 2013-12-31  2013
239  1.652895e+08 2013-12-31  2013
240  4.000000e+06 2018-12-31  2018
242  5.366728e+07 2013-12-31  2013
243  1.233027e+09 2018-12-31  2018
244  3.000000e+07 2013-12-31  2013
245  1.636332e+07 2015-12-31  2015
247  9.127504e+07 2013-12-31  2013
250  1.000000e+08 2013-12-31  2013
251  1.000000e+07 2013-12-31  2013
252  0.000000e+00 2018-12-31  2018
253  1.000000e+05 2013-12-31  2013
254  1.000000e+06 2013-12-31  2013

[186 rows x 10 columns]

In [30]:
#df2013.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2013.xlsx')
#df2014.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2014.xlsx')
#df2015.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2015.xlsx')
#df2016.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2016.xlsx')
#df2017.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2017.xlsx')
#df2018.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\2018.xlsx')

In [31]:
print(df2013.shape,df2014.shape,df2015.shape,df2016.shape,df2017.shape,df2018.shape)

(186, 10) (186, 10) (186, 10) (186, 10) (186, 10) (186, 10)

# 6个小表的持股占比合并到另一个表里
* 年份修改同一修改

In [32]:
# 指定第一列为索引
df6 = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\完成表.xlsx',index_col=0)

In [33]:
# 去掉.SZ
def removeSt(str):
    return str[0:-3]

In [34]:
df2013['代码'] = df2013['代码'].apply(removeSt)
df2014['代码'] = df2014['代码'].apply(removeSt)
df2015['代码'] = df2015['代码'].apply(removeSt)
df2016['代码'] = df2016['代码'].apply(removeSt)
df2017['代码'] = df2017['代码'].apply(removeSt)
df2018['代码'] = df2018['代码'].apply(removeSt)

In [35]:
# 修改年份
df2013['year'] = '2013-12-31'
df2014['year'] = '2014-12-31'
df2015['year'] = '2015-12-31'
df2016['year'] = '2016-12-31'
df2017['year'] = '2017-12-31'
df2018['year'] = '2018-12-31'

In [36]:
# ID生成
def createId(df,col1,col2):
    df['ID'] = df.loc[:,col1]+df.loc[:,col2]

In [37]:
createId(df2013,'代码','year')
createId(df2014,'代码','year')
createId(df2015,'代码','year')
createId(df2016,'代码','year')
createId(df2017,'代码','year')
createId(df2018,'代码','year')

In [38]:
# 合并持股比例到总表
df6['持股比例'] = None
# 把ID和索引做成字典方便检索
dt = dict(zip(df6['ID'].values,df6['ID'].index))

In [39]:
# 找出有ID的两个表的索引
ttt = 0
def combineDfRate(df,df1,colName):
    for idx in df1.index:
        id =df1.loc[idx,'ID']
        if id in dt:
            print(id)
            global ttt
            ttt+=1
            df.loc[dt[id],colName] = df1.loc[idx,colName]
    return df

In [40]:
df6 = combineDfRate(df6,df2013,'持股比例')
df6 = combineDfRate(df6,df2014,'持股比例')
df6 = combineDfRate(df6,df2015,'持股比例')
df6 = combineDfRate(df6,df2016,'持股比例')
df6 = combineDfRate(df6,df2017,'持股比例')
df6 = combineDfRate(df6,df2018,'持股比例')

0003012014-12-31
0005132014-12-31
0005162014-12-31
0007002014-12-31
0007962014-12-31
0008212014-12-31
0009972014-12-31
0020122014-12-31
0020422014-12-31
0020752014-12-31
0020932014-12-31
0020942014-12-31
0021082014-12-31
0021112014-12-31
0021182014-12-31
0021322014-12-31
0021762014-12-31
0021772014-12-31
0022292014-12-31
0022692014-12-31
0022772014-12-31
0022862014-12-31
0022872014-12-31
0022982014-12-31
0023472014-12-31
0023912014-12-31
0023972014-12-31
0024242014-12-31
0024472014-12-31
0024782014-12-31
0025262014-12-31
0025432014-12-31
0025672014-12-31
0025852014-12-31
0025922014-12-31
0026342014-12-31
0026612014-12-31
0026992014-12-31
3003372014-12-31
6000952014-12-31
6001672014-12-31
6001912014-12-31
6001962014-12-31
6002772014-12-31
6002882014-12-31
6003632014-12-31
6003802014-12-31
6005072014-12-31
6005712014-12-31
6005862014-12-31
6006552014-12-31
6006942014-12-31
6007782014-12-31
6007852014-12-31
6008182014-12-31
6008962014-12-31
6012162014-12-31
0003012015-12-31
0005132015-12-31
0005162015-12-31
0006262015-12-31
0007002015-12-31
0009672015-12-31
0020712015-12-31
0020752015-12-31
0020932015-12-31
0020942015-12-31
0021082015-12-31
0021322015-12-31
0021662015-12-31
0021762015-12-31
0021772015-12-31
0022292015-12-31
0022692015-12-31
0022862015-12-31
0022872015-12-31
0023472015-12-31
0023912015-12-31
0023972015-12-31
0024242015-12-31
0024402015-12-31
0024472015-12-31
0024782015-12-31
0025242015-12-31
0025262015-12-31
0025432015-12-31
0025852015-12-31
0025922015-12-31
0026342015-12-31
0026992015-12-31
3003372015-12-31
6001672015-12-31
6001962015-12-31
6002772015-12-31
6002882015-12-31
6003632015-12-31
6003802015-12-31
6005072015-12-31
6005712015-12-31
6005862015-12-31
6006552015-12-31
6006942015-12-31
6007112015-12-31
6007782015-12-31
6007852015-12-31
6008182015-12-31
6008652015-12-31
6008732015-12-31
6008962015-12-31
6012162015-12-31
6017772015-12-31
0003012016-12-31
0005132016-12-31
0005162016-12-31
0005932016-12-31
0006262016-12-31
0007002016-12-31
0007962016-12-31
0009672016-12-31
0009972016-12-31
0020122016-12-31
0020212016-12-31
0020712016-12-31
0020752016-12-31
0020902016-12-31
0020932016-12-31
0020942016-12-31
0021042016-12-31
0021182016-12-31
0021662016-12-31
0022692016-12-31
0022772016-12-31
0022862016-12-31
0022872016-12-31
0023472016-12-31
0023912016-12-31
0023972016-12-31
0024242016-12-31
0024472016-12-31
0024602016-12-31
0025242016-12-31
0025432016-12-31
0025852016-12-31
0025922016-12-31
0026342016-12-31
0026742016-12-31
0027012016-12-31
3003372016-12-31
3003662016-12-31
6000692016-12-31
6001362016-12-31
6001752016-12-31
6001912016-12-31
6002882016-12-31
6003662016-12-31
6003802016-12-31
6004672016-12-31
6005712016-12-31
6005862016-12-31
6006942016-12-31
6007112016-12-31
6007702016-12-31
6008652016-12-31
6008732016-12-31
6012162016-12-31
6017772016-12-31
0005162017-12-31
0005592017-12-31
0005932017-12-31
0006262017-12-31
0007002017-12-31
0007962017-12-31
0008212017-12-31
0009972017-12-31
0020712017-12-31
0020752017-12-31
0020932017-12-31
0020942017-12-31
0021042017-12-31
0021182017-12-31
0021662017-12-31
0021762017-12-31
0021772017-12-31
0021932017-12-31
0022692017-12-31
0022772017-12-31
0022862017-12-31
0022872017-12-31
0023912017-12-31
0023972017-12-31
0024242017-12-31
0024782017-12-31
0025242017-12-31
0025822017-12-31
0025852017-12-31
0025922017-12-31
0026242017-12-31
0026342017-12-31
0026742017-12-31
0026992017-12-31
3001092017-12-31
3003372017-12-31
6000692017-12-31
6000952017-12-31
6001102017-12-31
6001362017-12-31
6001672017-12-31
6002552017-12-31
6002882017-12-31
6005712017-12-31
6005862017-12-31
6006552017-12-31
6006942017-12-31
6007112017-12-31
6007702017-12-31
6008652017-12-31
6008732017-12-31
6012162017-12-31
6017772017-12-31
0006152018-12-31
0006262018-12-31
0007002018-12-31
0007822018-12-31
0007962018-12-31
0009972018-12-31
0020422018-12-31
0020932018-12-31
0020942018-12-31
0021182018-12-31
0021452018-12-31
0021662018-12-31
0021772018-12-31
0021932018-12-31
0022292018-12-31
0022772018-12-31
0022872018-12-31
0023912018-12-31
0023972018-12-31
0024242018-12-31
0024372018-12-31
0024602018-12-31
0025242018-12-31
0025852018-12-31
0025922018-12-31
0026242018-12-31
0026342018-12-31
0026742018-12-31
3003372018-12-31
3003482018-12-31
3003662018-12-31
6000692018-12-31
6000952018-12-31
6001672018-12-31
6001752018-12-31
6002262018-12-31
6002772018-12-31
6002882018-12-31
6003662018-12-31
6003802018-12-31
6005712018-12-31
6005862018-12-31
6006822018-12-31
6006942018-12-31
6007112018-12-31
6012162018-12-31
6017772018-12-31

In [41]:
#df6.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\汇总表持股比例.xlsx')

In [66]:
df6.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\汇总表持股比例未删减版.xlsx')

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\WuChuPeng\\Desktop\\其他\\宁静\\汇总表持股比例未删减版.xlsx'

In [67]:
dfidx = pd.read_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\编号(1).xlsx')

In [63]:
stocks = np.append(dfidx.iloc[:,0].values,301)

In [49]:
df6.head()

,Stkcd,Reptdt,Stknme,Nindcd,Nindnme,A001000000,ID,Accper,Typrep,F050203B,dir,C002006000,F081701B,F011201A,持股比例
10,5,2018-12-31,世纪星源,N77,生态保护和环境治理业,3.121423e+09,0000052018-12-31,2018-12-31,A,0.051959,0.357143,1.679095e+07,-0.084271,0.494040,None
16,8,2014-12-31,宝利来,H61,住宿业,6.740280e+08,0000082014-12-31,2014-12-31,A,0.011942,0.428571,2.851638e+06,0.008977,0.112276,None
18,8,2016-12-31,神州高铁,C37,铁路、船舶、航空航天和其它运输设备制造业,8.192657e+09,0000082016-12-31,2016-12-31,A,0.090060,0.428571,6.028932e+07,0.448569,0.246583,None
19,8,2017-12-31,神州高铁,C37,铁路、船舶、航空航天和其它运输设备制造业,1.067832e+10,0000082017-12-31,2017-12-31,A,0.094283,0.428571,5.718175e+07,0.242497,0.326949,None
21,9,2014-12-31,中国宝安,S90,综合,1.472550e+10,0000092014-12-31,2014-12-31,A,0.033352,0.428571,6.434760e+08,0.037654,0.628934,None

In [64]:
# 索引过滤
newDf = df6[[t in stocks for t in df6.iloc[:,0].values]]

In [68]:
newDf.to_excel(r'C:\Users\WuChuPeng\Desktop\其他\宁静\汇总表持股比例96未删减版.xlsx')